version: "0.1"
name: datawaves
services:
  auth-db:
    image: redis:latest
    ports:
    - "6379:6379"
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --loglevel warning
  auth:
    image: datawaves-auth:latest
    user: root
    volumes:
    - ./private.pem:/work/private.pem
    - ./publickey.pem:/work/publickey.pem
    - ./auth.properties:/work/config/application.properties
    ports:
    - "8080:8080"
    depends_on:
    - auth-db
  experimenter-db:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=datawaves
    - POSTGRES_PASSWORD=test.123
  experimenter:
    image: datawaves-experimenter:latest
    user: root
    volumes:
    - ./publickey.pem:/work/publickey.pem
    - ./exp.properties:/work/config/application.properties
    ports:
    - "8081:8081"
    depends_on:
    - auth
    - experimenter-db
  